/*
  Build: tsc for the package modules, esbuild for the two browser bundles,
  then bake the bundles (and html2canvas) into dist/core/assets.js so the
  handler serves them from memory — no filesystem reads at runtime.
*/
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { build } from "esbuild";

const root = resolve(import.meta.dirname, "..");
const r = (p) => resolve(root, p);

execSync("npx tsc -p tsconfig.json", { cwd: root, stdio: "inherit" });

const common = {
  bundle: true,
  format: "iife",
  target: ["es2019"],
  minify: true,
  legalComments: "none",
  external: ["html2canvas-pro"],
  logLevel: "warning",
};
await build({ ...common, entryPoints: [r("src/widget/index.ts")], outfile: r("dist/widget.js") });
await build({ ...common, entryPoints: [r("src/queue/client.ts")], outfile: r("dist/queue.js") });

const assets = {
  "widget.js": readFileSync(r("dist/widget.js"), "utf8"),
  "queue.js": readFileSync(r("dist/queue.js"), "utf8"),
  "html2canvas.js": readFileSync(r("node_modules/html2canvas-pro/dist/html2canvas-pro.min.js"), "utf8"),
};
const out =
  `/* generated by scripts/build.mjs — do not edit */\n` +
  `export const assets = ${JSON.stringify(assets)};\n` +
  `export const assetTypes = ${JSON.stringify({
    "widget.js": "text/javascript; charset=utf-8",
    "queue.js": "text/javascript; charset=utf-8",
    "html2canvas.js": "text/javascript; charset=utf-8",
  })};\n`;
writeFileSync(r("dist/core/assets.js"), out);
for (const [k, v] of Object.entries(assets)) console.log(`${k.padEnd(16)} ${(v.length / 1024).toFixed(1)} KB`);
